### ISSUE TITLE
Headers support

### ISSUE THREAD

**Issue by onemanstartup** [IdeasOnCanvas/Ashton#12]
Can I with Ashton make header support?
I see there is no ashton intermediate header representations.
If i read `<b>Wow!</b> Now <em>iOS</em> can create <h3>NSAttributedString</h3> from HTMLs!` markdown output would be `"**Wow**! Now *iOS* can create\n\n**NSAttributedString**\n\nfrom HTMLs!\n\n"` but it will be cool if output can be the same as input string.

Sorry, I'm not quite understand how attributedString work yet.
Thanks.

**Comment by aquarius** [comment]
As this request has been open for some time and as we don't require it for our own app, I'll close this issue. If you require this feature please reopen the issue and attach a PR. Thank you.
