### ISSUE TITLE
lineHeightMultiple

### ISSUE THREAD

**Issue by chlach** [IdeasOnCanvas/Ashton#38]
Thank your for this amazing API.
Could you please add support for ".**lineHeightMultiple**" it's a part of ( NSMutableParagraphStyle key ) 

To adjust line height

**Comment by schwmi** [comment]
Hi, thanks for your feedback. Sounds like a nice and useful addition. I would gladly accept PRs for that issue (due to time restrictions I am not able to add this feature by myself)

**Comment by aquarius** [comment]
Closed due to inactivity. If there is still interest in this feature, please reopen and submit a PR. Thank you.
